BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Farms] ADD [description] NVARCHAR(1000) CONSTRAINT [Farms_description_df] DEFAULT '',
[location] NVARCHAR(1000) CONSTRAINT [Farms_location_df] DEFAULT '',
[size] FLOAT(53) CONSTRAINT [Farms_size_df] DEFAULT 0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
